package com.goeswhere.tt;

import java.util.Set;

import com.google.common.collect.ImmutableSet;

public class SampleNicks {
//	final Set<String> names = dao.names();
//	Set<String> names2 = Sets.newHashSet();
//	for (String s : names)
//		names2.add(s.substring(0, Math.min(s.length(), 5)));
//	for (String s : names2)
//		System.out.println("\"" + s.replaceAll("\\\\", "\\\\\\\\") + "\",");

	final static Set<String> NICKS = ImmutableSet.of("MDand", "Yeti", "Prost", "Skill", "B2H", "Prosp", "Emrek",
			"olive", "cepas", "CoolG", "GUY O", "Mg320", "Deliv", "mathe", "samu3", "mc015", "X-ZeY", "Jaro", "Eleph",
			"Gun-1", "labar", "Romes", "Mr.Ba", "saw49", "Syek", "FALE", "kerom", "Cool ", "vgg", "antoi", "alex",
			"Hoho", "Taska", "Rui11", "t2har", "Afrol", "rmgdu", "truck", "debus", "john", "neo", "gayde", "vempi",
			"MLope", "fdeze", "M.I.", "Activ", "DtMag", "ART", "yello", "helio", "Badar", "madma", "drjan", "Lizar",
			"bart", "br_qu", "broke", "Fer", "papip", "portu", "Reive", "maxhd", "CHiNa", "Whisk", "GodFa", "Hosti",
			"LoKkO", "kev68", "klauz", "Steam", "Slowt", "rodri", "gaybo", "MurrP", "TheDA", "sDs", "Skala", "Loony",
			"Bide", "Humun", "Xmort", "IHD", "Ricar", "MSapa", "Russi", "gonza", "Adam", "Wolvo", "PACO_", "mazas",
			"DANNE", "Shott", "gnomi", "Andre", "Doc_m", "MonsT", "gnome", "[PT]G", "Jaans", "P1T3R", "ppard", "Walke",
			"Wazaa", "DeeJa", "marc4", "iNDIO", "Tekas", "[PT] ", "ethan", "Celia", "C4LO-", "MoesT", "Helli", "kaedi",
			"Kompi", "NffS", "freak", "MFM", "scani", "Earl", "Orfo", "Tigre", "Jakg", "pau f", "matov", "thale",
			"redev", "Cesar", "gendo", "eso1", "subar", "Axy", "Samon", "Colou", "InesD", "Bazil", "zigou", "Mango",
			"Mar*a", "ilman", "Joeim", "EPIC", "BATVA", "namba", "Doc_M", "pisto", "BSPL", "JFish", "scape", "shawn",
			"jon b", "Biven", "psant", "jacin", "fonfi", "zoef", "Tinma", "compa", "roboc", "Sathy", "nigmu", "....:",
			"lorek", "picte", "Arnes", "denni", "the13", "jpm", "Flori", "Wulth", "tito", "Yan_m", "Manch", "zmeta",
			"king2", "Kills", "gaby ", "***", "Who's", "Wisbo", "PoHaN", "PiXeL", "fires", "ilche", "Greya", "JJR#2",
			"dammm", "3433", "croat", "Bid d", "Jimbo", "OLega", "Wheel", "DANTE", "didid", "Dexte", "Augus", "BlacK",
			"RRSil", "sieci", "Frank", "ToTTe", "PRZEM", "ddgvc", "Sam.C", "ZEZE", "andre", "zajec", "G-Cha", "Ascal",
			"Franf", "Black", "cma_s", "Ricky", "RoTcE", "NAD45", "beerf", "Rickf", "vidol", "borja", "bity", "max 1",
			"Peki", "KAFF", "NoMaK", "ceran", "bloom", "Tiyug", "RODDI", "ElSti", "Stef", "Venta", "Bunif", "rody",
			"30STO", "Txemo", "KAR", "marki", "Zwil", "moore", "LCom", "hassa", "fale.", "Humil", "muhsi", "Carlo",
			"12111", "SILVI", "DracR", "Chyma", "BBC", "SANDO", "hide", "darko", "mehme", "ruben", "Midni", "TLC",
			"Cruz_", "Piotr", "Fear-", "cool", "*V*Hu", "~Undu", "Thiag", "RECO", "Steve", "Siggi", "Sagot", "GEEZE",
			"suomi", "OIDIL", "torpe", "ele m", "Fusca", "calld", "Mothe", "denis", "DKs", "HALVE", "ifThe", "Moter",
			"FlOzN", "Kryk", "chase", "Senor", "IgorP", "aAale", "IVANO", "hOt", "ac3ja", "Gelo", "Pinhe", "[UWCS",
			"Grave", "Neodi", "Sim", "jordi", "ashle", "ENZSC", "Gilmo", "Cille", "TaNe", "BFA", "pusca", "Bitne",
			"maste", "panas", "Almy", "coe", "gta 4", "xeonc", "torre", "simon", "aaaaa", "world", "Mupo", "Alewa",
			"SupSu", "Radzi", "nezhi", "chalu", "MinD", "Kaloy", "Plane", "Dirt_", "Slavi", "Lukas", "PT-Je", "Slava",
			"MrCdk", "gono", "ion", "jheff", "Alexe", "papa_", "Tim11", "sparc", "Alexa", "Radyo", "litos", "Trail",
			"Coiso", "DasId", "binge", "Barbo", "Lucas", "inscr", "Diaz", "SpaRr", "Fox R", "BUMI", "Rapto", "Void",
			"xandi", "ze_lu", "Maksi", "bobch", "Luke.", "Dark-", "nelso", "irmar", "B.Ric", "Tomek", "Dorgx", "becas",
			"Jaba0", "bobby", "thoma", "WooQa", "pooka", "Awasa", "max91", "uranu", "Erics", "Davil", "Molik", "DarkD",
			"vittu", "NMPSA", "lolin", "Mixig", "Pocak", "MRFJC", "Capim", "ninja", "Verbl", "DarkS", "DarkR", "Alex8",
			"Titor", "Rets", "pebro", "slepo", "Cance", "egemo", "darch", "*-* L", "MXMP", "Fred", "Quim ", "FILIP",
			"crew_", "quim_", "SHIT1", "5p1k8", "WarTo", "w0t", "Delak", "Fozli", "unq", "kisko", "yevin", "altoi",
			"rniba", "PiTko", "Truck", "*ett", "JUGAD", "Mark&", "Andr*", "cotz.", "DSV", "gusty", "Spice", "phoph",
			"axel@", "Dinka", "gamem", "Meral", "jonos", "Radki", "corvo", "Dude ", "Wakma", "cOlz.", "Roger", "DrHap",
			"Ecko1", "Next", "m0oyo", "Speci", "DIMAN", "Kowal", "oLOLO", "memem", "certi", "thiag", "batis", "cody",
			"CP44", "fat-b", "Afons", "*truc", "tinon", "kosio", "Howlw", "Mikie", "}:) P", "drucu", "vell", "Pedro",
			"CP22", "Presc", "Rockf", "Tobbl", "RODRI", "antma", "Mbro", "pues ", "Z0Z0", "808CR", "Jon", "b2h",
			"Jorgi", "Marci", "Jorge", "3l_pu", "37*pt", "Gener", "iRaci", "Nijlh", "Dima", "Ruben", "caedu", "oskar",
			"downl", "Akina", "yuras", "mytho", "Marca", "maxto", "Loko", "anto_", "Gundy", "SQDK", "lacle", "alpii",
			"Hard_", "Pate", "AABM", "Mikov", "Big A", "DAIKO", "Rings", "123fa", "kolin", "juhaa", "Knigh", "ross_",
			"Klaio", "hydse", "Chuck", "Nemon", "Pavli", "Tiago", "Hotpi", "-----", "Ringa", "f0ssa", "*Sele", "-kaze",
			"DA3DP", "pablo", "Viper", "vesgo", "FUCKE", "yomam", "iCat", "rui_p", "igor2", "boby", "agarr", "alexb",
			"alexd", "kufla", "-sHen", "Ketch", "RoChu", "Vitun", "Lion", "juanm", "ash20", "M_A_R", "PORTU", "Morta",
			"plavo", "juM8o", "Babyl", "ofek1", "RPB", "xzxzx", "e2asa", "TRUCK", "Jward", "Luis ", "zombi", "HP_DU",
			"Saube", "juan ", "Bikto", "psyki", "hard ", "pimme", "RJAG", "abaqu", "Banis", "tommy", "Bernn", "Johnn",
			"odi", "Pangu", "Tulio", "Linus", "juuul", "DIDO_", "kolds", "LilFr", "Berna", "Adish", "Idiot", "Kosty",
			"arche", "daba", "OPIE ", "Avoni", "[LRT]", "Sheri", "z* cR", "diogo", "Late", "H34oB", "mreq", "Demon",
			"Guilh", "jonyb", "Anark", "Musta", "po_ta", "sgtri", "Ivan'", "HUBOO", "djmon", "KAZAR", "drago", "wasab",
			"rxave", "aLvaR", "Najdo", "pedro", "Gucio", "SAMSP", "muris", "Ronni", "lucas", "wRsoU", "Mokos", "SLONI",
			"steph", "korpp", "Shuri", "stepa", "giggi", "danie", "Escad", "Tarbb", "Leal8", "grzes", "Raven", "Ottoo",
			"Nillo", "lucaf", "fundo", "Danii", "Haled", "AUTEC", "x-ray", "RFR", "pluto", "Palla", "sanxi", "scott",
			"Sante", "TonL", "LARDE", "Bruno", "Bruni", "hitma", "Soope", "TDi", "Anxuj", "Halda", "Fires", "Acid_",
			"No Na", "el mo", "Magic", "Gfer", "Hugo_", "M3Hen", "Eivan", "Krill", "tgm_2", "TDL", "Fire_", "Ganze",
			"hey d", "isado", "fucke", "Indie", "LEETP", "el ji", "MAXX", "Miau ", "poork", "jjcm", "Psha", "Brad",
			"M733", "prior", "dorks", "donke", "DES", "Music", "Nitro", "Filip", "Orang", "hamza", "Peril", "Patri",
			"BTX5", "sehen", "spill", "Olive", "Fungu", "banan", "Smoot", "Kai", "gonca", "Cabx", "Riple", "Eduar",
			"santo", "1745", "serj", "RafaL", "rapha", "staga", "pittr", "bugar", "RafaP", "Torpe", "regis", "/\\/!|",
			"mould", "Taras", "REG", "ultra", "Jnis", "miria", "LEONA", "DAVX9", "KILLE", "Rafal", "pyrom", "filip",
			"Guido", "stude", "b3ck", "jgbs", "Polyc", "smart", "Ben R", "Bubba", "MixMe", "ROSTS", "arrow", "Evolu",
			"Merzi", "Josep", "SWEET", "Matt", "JAD", "JAC", "reha", "edwba", "umid", "Chush", "Fabio", "marvi",
			"miudo", "CW98C", "*** *", "A.MOU", "anto", "bamba", "ochme", "jokin", "dude_", "tojok", "Rluis", "bruno",
			"[cff]", "Adrie", "Maste", "wesle", "Jarwi", "omosa", "Shini", "Anska", "dickh", "happy", "EDave", "Stupi",
			"lukii", "BR_Re", "joshu", "miihc", "FeLii", "Batma", "CACER", "Camp'", "HUMAN", "dude ", "MM111", "lizar",
			"Butch", "Trolo", "harry", "jocee", "marsh", "Artem", "Falko", "victo", "anoni", "camil", "I3UMI", "dtm",
			"Creat", "Omdi", "LOOOL", "ANDY", "Lux t", "Raive", "CANTE", "msn", "fedas", "d1man", "z-res", "Xairu",
			"kotlo", "xenon", "Broll", "Rolli", "FiR0N", "Shock", "OZGUR", "jacek", "graha", "Happy", "King_", "Vitin",
			"shait", "UNKIN", "Robbi", "sinis", "Pusca", "triks", "Vilge", "Henar", "drmr1", "dmcdj", "hallo", "Warra",
			"artur", "Migue", "defiu", "cena", "Brome", "Smart", "aleks", "Custo", "magwa", "Jotab", "marti", "WP24",
			"Jysky", "11111", "EXOTo", "laxro", "Ikari", "CRUNK", "Nande", "TicaT", "megaa", "CAP_N", "tempe", "MCLOU",
			"sober", "zzz", "mirro", "shine", "Lukc", "lenna", "carim", "Smexy", "tigga", "Under", "megaf", "vic",
			"Sando", "LUCAS", "ti6o", "sokin", "z3laz", "Rob", "nuno ", "Stoja", "xyu", "LELIS", "asd", "david",
			"costa", "DemaZ", "drake", "Vladi", "28g", "Lanks", "Drq", "Gerus", "sunsa", "Gambo", "Frenk", "kuzan",
			"Varde", "_D@ng", "masah", "halil", "Yaran", "Angel", "xXxSI", "Rober", "zarny", "Vlady", "Eno K", "tiago",
			"bmm7", "VYDAL", "mig", "BOZER", "g0dL1", "claud", "e.g.", "ibram", "Skumb", "Shado", "Guffe", "Sania",
			"CEMA", "mrCru", "Macho", "Devis", "Ediso", "Ang_c", "jay13", "=/JOL", "hique", "Divis", "Conno", "snupi",
			"mks", "DAGES", "SSTro", "jazzz", "MaXSt", "Pablo", "ELOY", "worf", "Wikto", "ukara", "Barre", "Das I",
			"defal", "JORA_", "RedPl", "gentr", "SIMOX", "luke", "sandy", "minib", "nunox", "Quali", "Nnand", "PeonS",
			"Abel", "Gerri", "ERI", "Meles", "_B@rc", "Sousa", "*****", "abcde", "Whitm", "LowRi", "shari", "Artof",
			"Kerwa", "Xende", "XaT4u", "Silvi", "Blood", "dude", "un_ki", "Gaara", "Dom", "Palad");
}
